export const DISPLAY_ALERT = 'SHOW_ALERT'

export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_SUBSCRIBER_BEGIN = 'REGISTER_SUBSCRIBER_BEGIN'
export const REGISTER_SUBSCRIBER_SUCCESS = 'REGISTER_SUBSCRIBER_SUCCESS'
export const REGISTER_SUBSCRIBER_ERROR = 'REGISTER_SUBSCRIBER_ERROR'
export const LOGIN_SUBSCRIBER_BEGIN = 'LOGIN_SUBSCRIBER_BEGIN'
export const LOGIN_SUBSCRIBER_SUCCESS = 'LOGIN_SUBSCRIBER_SUCCESS'
export const LOGIN_SUBSCRIBER_ERROR = 'LOGIN_SUBSCRIBER_ERROR'

